# Generated by Django 4.1 on 2023-07-03 08:50

import datetime
from django.db import migrations, models
import django.utils.timezone
import seminardetails.models


class Migration(migrations.Migration):

    dependencies = [
        ('seminardetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('active', models.BooleanField(default=True)),
                ('deactivation_date', models.DateField(default=datetime.datetime(2023, 12, 30, 8, 49, 38, 744331))),
            ],
        ),
        migrations.AddField(
            model_name='seminar',
            name='batch_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seminar',
            name='status',
            field=models.IntegerField(choices=[(0, 'Rejected'), (1, 'Submitted'), (2, 'Approved')], default=1),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='upload_file',
            field=models.FileField(max_length=254, upload_to=seminardetails.models.get_file_path),
        ),
    ]
