# Generated by Django 3.2.19 on 2023-08-16 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminardetails', '0005_batchusermapping_rename_batch_id_seminar_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='remarks',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='batch',
            name='deactivation_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 12, 14, 40, 53, 420060)),
        ),
    ]
