# Generated by Django 4.1 on 2023-07-03 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('project_title', models.CharField(max_length=130)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tools', models.CharField(blank=True, max_length=30)),
                ('abstract', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'Unapproved'), (1, 'Submitted'), (2, 'Approved')], default=1)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
    ]
