# Generated by Django 4.2.4 on 2023-08-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='author',
            new_name='created_by',
        ),
    ]
